server:
  port: 11004

spring:
  application:
    name: rocketmq-produce
  cloud:
    stream:
      rocketmq:
        binder:
          # RocketMQ 服务地址
          name-server: 121.199.58.19:9876
        bindings:
          output:
            producer:
              group: produce-group
              vipChannelEnabled: false
          output2:
            producer:
              group: produce-group2
              vipChannelEnabled: false
      bindings:
        output:
          destination: ehutong-pub-topic
          content-type: application/json
logging:
  level:
    org:
      springframework:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG
