server:
  port: 11003

spring:
  application:
    name: rocketmq-consume
  cloud:
    stream:
      rocketmq:
        binder:
          # RocketMQ 服务器地址
          name-server: 121.199.58.19:9876
        bindings:
          input2:
            consumer:
              #增加tag过滤
              tags: tagObj
      bindings:
        input:
          destination: ehutong-pub-topic
          content-type: text/plain
          group: consume-group1
          consumer:
            #并发消费线程数
            concurrency: 20
        input2:
          destination: ehutong-pub-topic
          content-type: application/json
          group: consume-group2
          consumer:
            #并发消费线程数
            concurrency: 20
        input3:
          destination: ehutong-pub-topic
          content-type: text/plain
          group: consume-group3
          consumer:
            #并发消费线程数
            concurrency: 20
